apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: poison-pill-manager
    namespace: poison-pill
spec:
    channel: alpha
    name: poison-pill-manager
    source: redhat-operators
    sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: poison-pill-manager
  namespace: poison-pill
spec:
  targetNamespaces:
  - poison-pill